### PR TITLE
Upgrade to Conan 2

### PR DESCRIPTION
**Pull request by kyllingstad**
This is just #55 again. I reverted that pull request because it depends on open-simulation-platform/libcosim#753, which is not in a release yet. (More details in [this comment](https://github.com/open-simulation-platform/libcosimc/pull/55#discussion_r1568907275).)

We have to choose between these two options:
1. Make a new libcosim release before merging this, so libcosimc `master` can continue to use the `libcosim@osp/stable` package.
2. Switch to using `libcosim@osp/testing` (which tracks libcosim `master`) in libcosimc `master`.

### CODE REVIEW

**Comment by kyllingstad** [comment]
Aw man, `master` is still broken despite the fact that I reverted all my changes to it. The problem is that our dependencies have moved on and no longer support the Conan version we use in our CI setup. That makes it all the more urgent to resolve the questions above and get this merged (again).

**Review by restenb — APPROVED** [review]
Now that libcosim is released, guess it's time to get around to this so we can release libcosimc. I have updated versions of libcosim and doxygen, and the builds started working again.

**Comment by restenb** [comment]
> This is just #55 again. I reverted that pull request because it depends on [open-simulation-platform/libcosim#753](https://github.com/open-simulation-platform/libcosim/pull/753), which is not in a release yet. (More details in [this comment](https://github.com/open-simulation-platform/libcosimc/pull/55#discussion_r1568907275).)
> 
> We have to choose between these two options:
> 
> 1. Make a new libcosim release before merging this, so libcosimc `master` can continue to use the `libcosim@osp/stable` package.
> 2. Switch to using `libcosim@osp/testing` (which tracks libcosim `master`) in libcosimc `master`.

I'm in favor of sticking to the stable release version of `libcosim` for `libcosimc` master, at least.

**Comment by kyllingstad** [comment]
Thanks for updating the PR, @restenb!

**Pull request merged**
